export const restaurants = [
  { name: "Spice Villa", rating: 4.5, cuisine: "Indian", time: "30-40 mins" },
  { name: "Sushi Hub", rating: 4.2, cuisine: "Japanese", time: "25-35 mins" },
  { name: "Pasta Palace", rating: 4.7, cuisine: "Italian", time: "20-30 mins" },
  { name: "Burger Town", rating: 4.0, cuisine: "American", time: "15-25 mins" },
  { name: "Tandoori Treats", rating: 4.3, cuisine: "Indian", time: "30-45 mins" },
  { name: "Dragon Wok", rating: 4.6, cuisine: "Chinese", time: "20-30 mins" },
  { name: "Pizza Mania", rating: 4.4, cuisine: "Italian", time: "25-35 mins" },
  { name: "Falafel Express", rating: 4.1, cuisine: "Middle Eastern", time: "20-30 mins" },
  { name: "Curry House", rating: 4.8, cuisine: "Indian", time: "35-45 mins" },
  { name: "Taco Fiesta", rating: 3.9, cuisine: "Mexican", time: "15-25 mins" },
  { name: "BBQ Nation", rating: 4.5, cuisine: "BBQ", time: "40-50 mins" },
  { name: "Veggie Delight", rating: 4.3, cuisine: "Vegetarian", time: "20-30 mins" },
  { name: "Biryani Bazaar", rating: 4.7, cuisine: "Indian", time: "30-40 mins" },
  { name: "Ramen Corner", rating: 4.2, cuisine: "Japanese", time: "25-35 mins" },
  { name: "Shawarma King", rating: 4.0, cuisine: "Middle Eastern", time: "20-30 mins" },
  { name: "Street Dosa", rating: 4.6, cuisine: "South Indian", time: "20-25 mins" },
  { name: "Noodle Nest", rating: 4.1, cuisine: "Chinese", time: "15-20 mins" },
  { name: "Cheese Factory", rating: 3.8, cuisine: "Fast Food", time: "10-20 mins" },
  { name: "Grill & Chill", rating: 4.4, cuisine: "Continental", time: "30-40 mins" },
  { name: "Healthy Bites", rating: 4.5, cuisine: "Salads & Healthy", time: "20-30 mins" }
];
